version: "2.0"
endpoints:
 deraendpoint:
   kind: ip
services:
  diode:
    image: tuhalf/diode_server
    expose:
      - port: 41046
        to:
          - global: true  
            ip: deraendpoint
      - port: 443
        to:
          - global: true 
            ip: deraendpoint 
      - port: 993
        to:
          - global: true  
            ip: deraendpoint
      - port: 1723
        to:
          - global: true  
            ip: deraendpoint
      - port: 10000
        to:
          - global: true  
            ip: deraendpoint
      - port: 51054
        to:
          - global: true  
            ip: deraendpoint
    env:
      - WORKER_MODE=800 # CPU usage in percent. 100% = 1 core. values over 100% are for multi-core systems. 800 = 8 cores. setting Disabled will disable the worker.Recomended to set disabled in syncing period. 
      - BLOCKCHAIN_SQ3_URL=https://pub-0d5d49260e184f7aa3fbc5cffff1d889.r2.dev/snapshots/blockchain.sq3 # Blockchain snapshot url (optional but recommended for faster sync)
      #- PRIVATE=0x0000000000000000000000000000000000000000000000000000000000000000 # Your Wallet Private Key
    params:
      storage:
        data:
          mount: /diode_server/data_prod
      

profiles:
  compute:
    diode:
      resources:
        cpu:
          units: 8
        memory:
          size: 8Gi
        storage:
          - size: 10Gi
          - name: data
            size: 140Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    akash:
      attributes:
        ip-lease: "true"
      pricing:
        diode:
          denom: uakt
          amount: 10000

deployment:
  diode:
    akash:
      profile: diode
      count: 1