version: "3.9"
services:
  diode_server:
    image: tuhalf/diode_server
    container_name: diode_server
    restart: always
    ports:
      - "8545:8545"
      - "8443:8443"
      - "41046:41046"
      - "443:443"
      - "993:993"
      - "1723:1723"
      - "10000:10000"
      - "51054:51054"
    volumes:
      - data:/diode_server/data_prod
    environment:
      WORKER_MODE: 800 # CPU usage in percent. 100% = 1 core. values over 100% are for multi-core systems. 800 = 8 cores
      BLOCKCHAIN_SQ3_URL: https://pub-0d5d49260e184f7aa3fbc5cffff1d889.r2.dev/snapshots/blockchain.sq3 # Blockchain snapshot url (optional but recommended for faster sync)
      #PRIVATE: 0x0000000000000000000000000000000000000000000000000000000000000000 # Your Wallet Private Key
volumes:
  data: